### PR TITLE
Upgrade Gem plugin fluent-plugin-kubernetes_metadata_filter

### PR DESCRIPTION
**Pull request by hervenicol**
towards: https://github.com/giantswarm/giantswarm/issues/21769

Upgrade Gem plugin fluent-plugin-kubernetes_metadata_filter from 2.6.0 to 2.10.0

## Checklist

- [X] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by TheoBrigitte — APPROVED** [review]

**Comment by weatherhog** [comment]
@hervenicol @TheoBrigitte I think it would make sense to update everything. I mean this has been last touched over one year ago. To provided our customers with up to date technologies we should also see what else can be updated.

**Review by QuentinBisson — APPROVED** [review]
LGTM if tested :)

**Comment by TheoBrigitte** [comment]
> @hervenicol @TheoBrigitte I think it would make sense to update everything. I mean this has been last touched over one year ago. To provided our customers with up to date technologies we should also see what else can be updated.

Maybe, yes but this need to be tested then.

**Comment by hervenicol** [comment]
No follow-up from customer, hence not tested. Closing for the moment.

**Pull request closed without merging**
